### ISSUE TITLE
Make object paths stable across restarts (of dleyna-renderer and of the DMR)

### ISSUE THREAD

**Issue by markdryan** [01org/dleyna-renderer#114]
Currently DMRes are identified by sequential integers which depends on the order they're first seen by dleyna-renderer (eg. /com/intel/dLeynaRenderer/server/2).

This means that it will be impossible to keep persistent references to objects across DMR or dleyna-renderer restarts, as media items will have paths like /com/intel/dLeynaRenderer/server/2/3034306130393764373063393261313636623936616133623835663332306334.

To address this we could use the udn as stable server identifier, eg. /com/intel/dLeynaRenderer/server/uuid/6da19ece-c964-4094-a2bd-84249e8c7da6.

To also allow for more compact and closer to the original representation of the media item identifiers something like tp_escape_as_identifier() could be employed, escaping only invalid characters instead of always doubling the required string length as done by prv_id_to_object_name().

(Text based on https://github.com/01org/dleyna-server/issues/119)

**Comment by rsbells** [comment]
This is resolved in #132 . Closing as duplicate
